# Generated by Django 5.1.6 on 2025-03-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
